### ISSUE TITLE
Evaluate RunPod deployment strategy for the GPU-intensive scanning pipeline

### ISSUE THREAD

**Issue by quevon24** [freelawproject/scanning#42]
## Context

The scanning pipeline has two GPU-heavy steps (`blackletter.detect` and `blackletter.analyze_pdf`) that we want to offload from the always-on CPU daemon onto rented GPU time. This issue compares the four realistic RunPod deployment strategies so we can pick one before committing more infrastructure work. Preliminary implementation targeting Serverless is already on the `feat/runpod-serverless` branch (scanning + `feat/ensure-weights` on blackletter).

### Option 1: RunPod Serverless

The daemon submits jobs to a Serverless endpoint. Workers spin up on demand, run one job, and die after an Idle Timeout window. The endpoint pulls a Docker image we push to a container registry. Input PDFs are handed to the worker as **presigned S3 GET URLs**, not raw AWS credentials.

**Advantages**
- Pay only when jobs are actually running. Zero cost while idle (assuming `Min Workers = 0`).
- No operational ownership: RunPod handles scheduling, capacity, retries, monitoring.
- Integration already implemented on the branch (`scanning/runpod_client.py`).
- Elastic: handles bursts by spawning concurrent workers.
- Single-toggle local fallback: daemon falls through to in-process blackletter when `RUNPOD_ENABLED=False`, so dev/CI are unaffected.
- **Tight security boundary on input access.** Presigned URLs are scoped to one specific S3 key, read-only, and expire after a configurable TTL. No AWS credentials are ever given to the worker. If a URL leaks (via logs, endpoint misconfiguration, registry compromise, etc.), the exposure is bounded to a single PDF for a limited time window, with no ability to list the bucket, write, or delete anything.

**Disadvantages**
- Queue-wait and cold-start times are unpredictable and can be multi-minute during busy hours.
- Each independent GPU call (detect, then analyze) risks its own cold start unless warm reuse kicks in.
- Presigned S3 URLs need a TTL long enough to survive queue + cold start (we are currently at 1 hour; max possible is 7 days).
- Pay-per-second rate on the 16 GB tier (A4000/A4500/RTX 2000 Ada/RTX 4000 Ada) is approximately `$0.00016/s ≈ $0.576/hr` of active worker time, which is more expensive per GPU-hour than renting a dedicated pod.

**Per-scan cost (measured on 1359-page volume, see Testing results below)**
- detect + analyze execution: ~$0.07
- Plus idle billing between/after calls (0 to $0.10): total ~$0.07 to ~$0.17 per scan.

**Requires**
- Docker image pushed to a registry (Docker Hub or GHCR).
- RunPod Serverless endpoint configured with GPU tier, Min/Max Workers, Idle Timeout.
- Env vars on the endpoint (`SENTRY_DSN_GPU`, `HANDLER_MAX_PAGES`, etc.).
- Daemon env vars (`RUNPOD_ENABLED`, `RUNPOD_ENDPOINT_ID`, `RUNPOD_API_KEY`, `RUNPOD_PRESIGNED_TTL`).
- S3 presigned GET URLs for the worker to read input PDFs.

---

### Option 2: Scheduled GPU pod (cron-based)

A dedicated GPU Pod is started on a fixed schedule (for example, 1 AM to 5 AM), processes whatever is in the queue, then stops. Controlled via `runpodctl` or the RunPod GraphQL API from a cron job.

**Advantages**
- GPU is guaranteed once the pod starts: no scheduler queue, no per-job cold start.
- Per-hour pricing is lower than Serverless: `$0.24 to $0.27/hr` for the 16 to 24 GB on-demand tier versus `$0.576/hr` equivalent on Serverless.
- Predictable: users know the processing window.
- Image and model weights persist on the pod's local disk between stops, so restarts are fast (seconds, not minutes).

**Disadvantages**
- Scans submitted outside the processing window sit in `QUEUED` until the next window. Unsuitable if users expect same-day feedback.
- We pay for the full window even if the queue is empty for part of it.
- Requires a different integration pattern on the daemon side: pods don't live behind `api.runpod.ai/v2/{endpoint}/run`, so `runpod_client.py` would need to talk directly to an HTTP server inside the pod (or we run the same `runpod.serverless.start` handler in the pod, see Option 4).
- A cron failure silently misses a processing window.

**Cost**
- Running 4 h/night on A4000 on-demand: `4 × $0.25 ≈ $1.00/day`.
- Running 8 h/night: ~$2.00/day.

**Requires**
- Cron job (on a scanning-owned server) or an equivalent scheduler.
- `runpodctl` or GraphQL API credentials for start/stop.
- Persistent pod definition.
- New integration in `runpod_client.py` to target a pod directly (or adoption of Option 4 to avoid this).

---

### Option 3: Daemon-triggered pod

The scanning daemon itself watches the `QUEUED` table; when non-empty, it calls the RunPod API to start a pod, dispatches scans to it, and stops the pod when the queue is empty.

**Advantages**
- Best cost profile of the pod options: pay only when there's actual work.
- GPU available on demand for each batch, with no queue-wait after startup.
- No reliance on a wall-clock schedule: responds to real load.
- Lower cost than always-on pods AND predictable availability.

**Disadvantages**
- The most code to own and debug. Needs state machine for pod lifecycle, health checks, startup timeouts, partial failures.
- First scan in a batch still pays the pod boot cost (2 to 5 min) before processing.
- Risk of pod-leak if the daemon crashes after starting the pod but before stopping it.
- Requires the same non-Serverless daemon integration as Option 2.

**Cost**
- Lower bound matches Serverless execution-only cost; upper bound is whatever the pod is active minus the per-hour-vs-per-second rate advantage. Break-even with Serverless at roughly 10 scans/day in a concentrated batch window.

**Requires**
- Pod lifecycle management code in the daemon.
- RunPod API credentials stored as a daemon env var.
- Failure-mode handling: pod failed to start, daemon crash, stuck pod, etc.
- New integration in `runpod_client.py` to target a pod directly (or Option 4).

---

### Option 4: GPU pod attached to the Serverless endpoint

A dedicated pod is attached to the Serverless endpoint as an "always-on worker." The daemon still calls `api.runpod.ai/v2/{endpoint}/run` exactly as in Option 1; RunPod routes work to the pod instead of a bursty Serverless pool. The pod can be scaled up/down on a schedule or kept 24/7.

**Advantages**
- Zero code change on the daemon side. Keeps everything we already built for Option 1.
- Zero cold-start ever: the pod is always warm.
- Same observability (RunPod dashboard, Sentry tagging, per-scan metrics).
- Can be combined with Option 2's cron scheduling to get Option 2 without the code rewrite.
- Same presigned-URL / no-AWS-creds security model as Option 1.

**Disadvantages**
- Most expensive if run 24/7: ~$6/day on A4000 on-demand, ~$180/month.
- Still subject to GPU scheduling at pod startup (but only on start, not per-job).
- Can't fully "turn off" without losing the pod-worker role unless we script the attach/detach. Scheduling helps here.

**Cost**
- 24/7: `$0.25/hr × 24 × 30 ≈ $180/month`.
- Scheduled 4 h/night: ~$30/month plus the existing Serverless bursty fallback outside that window.

**Requires**
- Everything Option 1 requires (image, endpoint, env vars, daemon wiring), already done.
- Additional pod attached to the endpoint via the RunPod console or API.
- Optional: cron job to start/stop the pod on a schedule.

---

## Comparison table

| Option | Upfront work | Ongoing cost (sporadic use) | Ongoing cost (40+ scans/day) | Cold start per job | Daemon code change |
|---|---|---|---|---|---|
| 1. Serverless | None (done) | ~$0.07 to $0.17/scan | ~$3 to $7/day | Likely | None |
| 2. Scheduled pod | Moderate (new integration) | ~$1 to $2/day fixed | ~$1 to $2/day fixed | Only on pod start | Yes |
| 3. Daemon-triggered pod | High (lifecycle code) | Low (pay only active) | Low | Only on first-of-batch | Yes |
| 4. Pod attached to endpoint | Low (zero code, just pod config) | $30/month (scheduled) to $180/month (24/7) | Flat | Never | None |

---

# Testing results from our Serverless implementation

All numbers below are from a single 1359-page case-reporter PDF processed against a Serverless endpoint with an RTX A4000/A4500 tier (16 GB VRAM) on RunPod, image pushed to a personal Docker Hub repo.

## Detect

| Field | Value |
|---|---|
| `status` | `COMPLETED` |
| `delayTime` (queue + worker boot) | 1,325,960 ms (~22 min) |
| `executionTime` (RunPod's view) | 317,131 ms (~5.3 min) |
| `duration_ms` (handler's view) | 297,808 ms (~5.0 min) |
| `worker_boot_ms` (cold-start cost) | 3,313 ms (~3.3 s) |
| `worker_uptime_ms` at job start | 318,311 ms |
| `gpu_available` | `true` |
| `page_count` | 1,359 |
| Response payload | 2.6 MB |

**Per-YOLO-model durations:**

| Model | Duration | Per-page |
|---|---|---|
| `small` (21 MB weights) | 84,557 ms (~84.6 s) | 62 ms/page |
| `medium` (49 MB weights) | 103,082 ms (~103.1 s) | 76 ms/page |
| `large` (148 MB weights) | 109,465 ms (~109.5 s) | 81 ms/page |

**Detection quality**
- Total detections: 10,057 across 1359 pages (~7.4/page).
- Every page has at least one detection.
- Multi-model agreement: 57% of detections found by all 3 models, 27% by 2, 9% by 1 only.

## Analyze (PaddleOCR + YOLO large)

| Field | Value |
|---|---|
| `status` | `COMPLETED` |
| `delayTime` | 567,055 ms (~9.5 min) |
| `executionTime` | 150,276 ms (~2.5 min) |
| `duration_ms` | 137,953 ms (~2.3 min) |
| `worker_boot_ms` | 3,258 ms (~3.3 s) |
| `gpu_available` | `true` |
| Response payload | 873 KB |

**Page-number detection quality**
- 1359/1359 pages (100%) received a detected page number.
- 1356 of those located via YOLO's page-number box (direct read).
- 3 via header-side fallback when YOLO missed.
- Zero anomalous jumps in the numeric sequence.

## Warm reuse

Both jobs in the same test run were dispatched to the **same worker** (`sywqhmmostejwk`). Analyze finished, the worker stayed `Idle` for the 5-minute Idle Timeout window, then the detect submission picked it up without a fresh cold start. This is the expected behavior for a single scan going through `run_full_pipeline` and confirms the client + endpoint wiring.

## Cost per 1359-page scan (at \$0.00016/s)

- Detect execution: 298 s × \$0.00016 = **\$0.048**
- Analyze execution: 138 s × \$0.00016 = **\$0.022**
- Cold boot per GPU call: ~3 s, ~\$0.001
- Idle between detect and analyze (up to 300 s): **\$0 to \$0.048**
- Idle after last call (up to 300 s until Idle Timeout): **\$0 to \$0.048**

**Total: ~\$0.07 to ~\$0.17 per full-pipeline scan**, depending on how long warm-idle billing runs.

## Issues encountered during Serverless implementation

All resolved on the branch, documented here for completeness.

1. **paddlepaddle-gpu vs torch CUDA conflict.** On long YOLO runs (1000+ pages), Paddle's idle CUDA allocator fired a cleanup pass while torch was driving the GPU, producing `cudaErrorInitializationError` and SIGABRT. Fix: removed PaddleOCR preload from `_preload()`. PaddleOCR now loads lazily on first analyze call (blackletter already does this). Detect-only workers never load Paddle at all.
2. **Worker being killed between jobs.** Initially thought to be a RunPod SDK bug; actually a misconfigured `Idle Timeout` of **5 seconds** instead of 300 s. Fix: set to 300 s in the endpoint config. Warm reuse now works.
3. **`Failed to get job. | missing field(s): id or input`** on `/runsync` submissions. Workers boot successfully, SDK then crashes on job dispatch. Fix: use `/run` (async + poll) from the daemon. `runpod_client.py` uses `/run` exclusively.
4. **Docker image originally 37.6 GB** due to uv's wheel cache being baked into the layer. Fix: `--mount=type=cache,target=/root/.cache/uv` + `uv sync --no-cache` in the Dockerfile. Now 22 GB uncompressed / 7.09 GB compressed (what Docker Hub stores and RunPod pulls).
5. **`libcuda.so.1` missing at build time**, breaks import of `paddlepaddle-gpu`. Fix: multi-stage `COPY --from=nvidia/cuda:*-devel-*` of the stub library. At runtime, RunPod's nvidia-container-toolkit bind-mounts the real `libcuda.so.1` over the stub.

## Open question: presigned URL TTL vs queue wait

Our current implementation generates presigned GET URLs for the worker to read input PDFs (no AWS credentials are given to the worker). Presigned URLs have a TTL; if RunPod's queue + cold-start exceeds that TTL, the worker gets a 403 when it finally tries to fetch the PDF.

Observed queue + boot times in our testing have reached 22 minutes. The current TTL is 1 hour, which is fine so far, but busy-hour scheduling could push it higher.

Mitigation options (to decide alongside the deployment option):

- **Bump TTL to the AWS SigV4 maximum of 7 days.** Zero code change, very low security impact (URL is still read-only, scoped to one specific S3 key, unguessable signature).
- **Give the worker scoped read-only IAM credentials instead of presigned URLs.** More code, slightly tighter security (revokable, auditable via CloudTrail).
- **Keep 1-hour TTL and add 403-retry logic on the daemon side.** Most code, only defends against URL expiry specifically.

**Comment by grossir** [comment]
This is great @quevon24 

I think option 1) Serverless would be preferable for one extra reason: user experience. The end user for this are the scanners. If they can get "immediate" feedback, they may correct errors on the same day they uploaded a scan. They don't need to wait for the next day to get the book again and correct any errors

On the other hand, maybe some of the cheaper approaches would be suitable for the "final" work once the scan is considered complete. That one could work on a schedule.

**Comment by mlissner** [comment]
Agree, great analysis, and agree: Option 1 is best. It's cheap enough ($400 for 2,000 books), and it is simple. I've also been hearing horror stories of test runs taking forever to iterate on your local computers. If a GPU in runpod is 10¢, we should be doing a lot more of that to make the DX better!

**Comment by quevon24** [comment]
## Pod test results (Option 3): `feat/runpod-pod` branch

I built out Option 3 on a new branch (`feat/runpod-pod`) and ran a manual smoke test against a real RunPod pod. Summary: the daemon-triggered-pod model has a structural problem on RunPod that makes it unsuitable for our use case.

### What worked

- Pod image (FastAPI + uvicorn wrapping the same blackletter actions): builds and runs.
- Bearer-auth on `/health`, `/warmup`, `/detect`, `/analyze`.
- Lifecycle from REST: `POST /v1/pods/{id}/start`, poll `GET /v1/pods/{id}`, `POST /stop`.
- Boot to ready in ~140s on a warm image (2s container + ~120s before the HTTP proxy URL was reachable).
- Warmup durations: yolo small/medium/large = 77/104/488 ms, paddle = 6259 ms.
- Detect (`small` only) on the same 1359-page volume used for the Serverless numbers above: 114s execution, 84 ms/page, GPU confirmed.

### Deal-breaker: pods are pinned to a single host

After the first stop+start cycle, the second start failed with:

```
{"error":"start pod: There are not enough free GPUs on the host machine to start this pod.","status":500}
```

RunPod assigns a pod to a specific physical host at creation time and tries to put it back on **that same host** on every restart. If another customer claimed that GPU during the idle window, the start fails and the pod stays stuck until either the original host frees up or you terminate and recreate the pod.

For the daemon-triggered model that's a hard problem:

1. Daemon stops the pod after 2 min idle.
2. 30 min later a scan arrives.
3. Daemon calls `POST /pods/{id}/start`. Fails with 500. Scan goes back to QUEUED.
4. Daemon retries on the next tick. Still fails. Loops indefinitely.
5. Operator has to manually terminate and recreate the pod (new pod ID, daemon needs reconfig).

Workarounds all have downsides:

- **Keep the pod running 24/7**: defeats the cost saving that motivated Option 3 in the first place.
- **Auto-terminate + recreate every cycle**: loses the boot speedup from a cached image, adds state-tracking complexity (pod ID changes), and there's no guarantee the new pod lands on a host with capacity either.
- **Use a less-contested GPU tier** (4000 Ada, 2000 Ada): may reduce frequency, doesn't fix the underlying pinning behavior.
- **Global Networking pods** (newer RunPod feature): theoretically allows the pod to move hosts, but I haven't confirmed it actually solves the start-time capacity problem versus just helping with networking. Worth a follow-up if we ever revisit.

### Secondary concerns also surfaced

- **RunPod's HTTP proxy URL has a ~100s idle timeout.** Analyze runs ~150s and detect-with-all-three-models is 5+ min, so the proxy closes the connection mid-call. Workaround would be exposing a TCP port and hitting the public IP directly, accepting plain HTTP + bearer token over the public internet.
- **Pod machines are smaller than serverless workers** (5 vCPUs in this test). Per-page detect was ~35% slower than the Serverless numbers in this issue, plausibly because PDF page decode is CPU-bound.

### Cost picture (revised)

The motivation for Option 3 was the per-hour rate gap ($0.25/hr pod vs. ~$0.576/hr equivalent serverless). But the pinning problem forces one of:

- Always-on pod (~$180/mo flat). Loses to serverless until ~30 scans/day.
- Daemon-triggered with manual recovery on every capacity miss: operationally untenable.
- Daemon-triggered with auto-recreate on failure: cost goes back up because every cycle pays full image-pull boot, and the operational complexity (tracking pod IDs, reconciling state) eats most of the engineering benefit of "we already have the serverless integration working."

**Comment by quevon24** [comment]
Thanks @grossir and @mlissner. I also agree with option 1.

A couple of notes

### Why Option 1 holds up
- Already implemented and measured: ~$0.07-0.17 per scan.
- Same-day feedback for scanners (the UX point @grossir raised).
- GPU tier is not a one-way door. The endpoint config in the RunPod panel lets us swap GPU types or add a fallback priority list (up to 3 tiers) without rebuilding or redeploying the image. If the 16 GB tier  becomes a bottleneck we can promote to A5000 24 GB in a few clicks.

### What stays in the daemon

Only `detect` and `analyze_pdf` go to the GPU worker. CPU-bound steps (bitonal conversion, OCR text extraction outside of Paddle, opinion pairing, file generation, redaction-rect math) keep running in the scanning daemon container. 

The reason for the split: Serverless bills per-second of GPU worker time at the GPU rate (~$0.576/hr-equivalent). Running CPU-only work on the worker would burn that rate on something a CPU container handles for free. The Serverless 16 GB tier worker has roughly 4-6 vCPUs (RunPod doesn't publish the exact number; our pod test on the same physical tier showed 5 vCPUs), which is plenty for the GPU-side preprocessing the worker actually needs to do but not what we'd want for the rest of the pipeline.

This is the model already implemented on the branch and I'd like to confirm both of you are OK with it before we lock in. The daemon hands the worker a **presigned S3 GET URL scoped to one specific object key, read-only, 1-hour TTL** (configurable up to 7 days, the AWS SigV4 max). The worker never receives AWS credentials.

### And why presigned URLs?

- If a URL leaks via logs, registry compromise, or RunPod endpoint misconfiguration, exposure is bounded to one PDF for at most the TTL window.
- No AWS credentials on the RunPod side at all.
